# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe3f1244a8442601df42a2dcf2cacc5c7d970b9a2c64bee053dd97643a26b40967cf269c8e92f4153bca00c8a8d1b47723e431e14a52e48c94e1a253cb8fb48c

test:
  secret_key_base: 56a2612f9605ad78c2758b2f2d7f50823d3e3728fa021d774646a9f0f40f8a1ed99b7d0b4f3c912150f5f6fd74a35e1ce3a93ee0dd2414b26e6c46359054f81c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
